# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Smilekids Cildcare Center
email: xkiwis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another Jekyll theme. It is designed for business purpose and ported by 
  Melvin Ch'ng.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://smilekidsvictoria.ca" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Anna song
address_line: 470 Belleville St, Victoria, BC V8V 1W9
telephone_number: 1.256.884.4126
#fax_number: 1.250.884.4126
company_email: xkiwis@gmail.com
google_map: https://goo.gl/maps/pXaSA8GSBSeP7RSv6

# Social Link
facebook_link: http://smilekidsvictoria.ca
twitter_link: http://smilekidsvictoria.ca
linkedin_link: http://smilekidsvictoria.ca
googleplus_link: http://smilekidsvictoria.ca

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
